cors:
  originPatterns: http://localhost:3000,http://localhost:8080
security:jwt:token:secret-key:53ccr37expire-lenght: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_springboot_courseapi?useTimezone=true&Timezone=UTC
    username: root
    password: Gui010203
  jpa:
    hibernate:
      ddl-auto: none
    #properties:
     # hibernate:
      #  dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false 
springdoc:
  swagger-ui:
    use-root-path: true
  paths-to-match:
  - /auth/**
  - /api/**/v1/**
spring.jpa.open-in-view: false
  

  